services:
  api:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app/chroma_data:/app/chroma_data
      - ./data:/app/data:ro
    env_file:
      - app/.env
    environment:
      - CHROMA_PERSIST_PATH=/app/chroma_data
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - ./app/chroma_data:/data